spring:
  datasource:
    url: jdbc:mysql://example.com:3306/wallet
    username: example
    password: "password"
    driver-class-name=com: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        order_inserts: true
        jdbc:
          batch_size: 100