spring:
  datasource:
    url: jdbc:mysql://example.com:3306/wallet
    username: example
    password: "password"
    driver-class-name=com: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false
        order_inserts: true
        jdbc:
          batch_size: 100
rpc-api:
  base-url: http://127.0.0.1:8080
  port: 8080
  endpoint: /api/v1/wallet

